<h1><div align=center>PYTHON FOR DATA SCIENCE LAB</div> </h1>
<h3><div align=right><b><u>Name: </u></b>M.R.Naveen Kumar
<div align=right><b><u>USN: </u></b> 19BTRCR005

Write Python program using NumPy

a. To find the addition of two matrices

b. To find the product of two matrices

c. To find the transpose of a matrix


In [3]:
import numpy as np

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(arr1,"\n",arr2)

[[1 2]
 [3 4]] 
 [[5 6]
 [7 8]]


In [14]:
print("Array Matrix addition- \n{}".format(arr1+arr2))

Array Matrix addition- 
[[ 6  8]
 [10 12]]


In [11]:
#using add() function
print("Array Matrix addition- \n{}".format(np.add(arr1,arr2)))

Array Matrix addition- 
[[ 6  8]
 [10 12]]


In [12]:
print ("The element wise multiplication of matrix is - \n{} ".format(np.multiply(arr1,arr2)))

The element wise multiplication of matrix is - 
[[ 5 12]
 [21 32]] 


In [13]:
print ("The Product of matrix is - \n{} ".format(np.dot(arr1,arr2)))

The Product of matrix is - 
[[19 22]
 [43 50]] 


In [10]:
mat1 = np.matrix(((1,2),(3,4)))
mat2 = np.matrix(((5,6),(7,8)))

add = mat1+mat2
dot = mat1*mat2

print("Addition of two matrices - \n{}".format(add))
print("\nProduct of two matrices - \n{}".format(dot))


Addition of two matrices - 
[[ 6  8]
 [10 12]]

Product of two matrices - 
[[19 22]
 [43 50]]


In [18]:
mat3 = np.matrix(((1,2,3),(4,5,6)))
print(mat3)
print("\nTranspose of the matrix - \n{}".format(mat3.T))

[[1 2 3]
 [4 5 6]]

Transpose of the matrix - 
[[1 4]
 [2 5]
 [3 6]]
