In [1]:
n=int(input())
dic = {}
for i in range(1,n+1):
    dic[i]=i*i
print(dic)


{1: 1, 2: 4, 3: 9, 4: 16}


In [2]:
d={i:i*i for i in range(1,11)}
print(d)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


In [3]:
d1={i:i*i for i in range(1,11) if i%2==0 & i%3==0}
print(d1)

{2: 4, 4: 16, 6: 36, 8: 64, 10: 100}


In [4]:
from datetime import *
dat = date.today()
print(dat,dat.month,dat.day,dat.year)

2021-09-22 9 22 2021


In [5]:
tim= datetime.now()
print(tim)


2021-09-22 11:15:37.549805


In [6]:
import numpy as np
arr = np.array([1,2,3,4])

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
print(np.zeros(5))
print(np.ones(5))
print(np.arange(5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 1 2 3 4]


In [9]:
print(type(np.ones(5)))

<class 'numpy.ndarray'>


In [10]:
x=np.ones(5,dtype=np.int64)
x

array([1, 1, 1, 1, 1], dtype=int64)

In [11]:
i = np.array([[1,2],[3,4]])
print(i)

[[1 2]
 [3 4]]


In [12]:
print(i.ndim)
print(i.size)
print(i.shape)

2
4
(2, 2)


In [13]:
a=np.array([1,2,3,4,5,6,7,8,9,0])
print(a)

[1 2 3 4 5 6 7 8 9 0]


In [14]:
print(a[0],a[-1])

1 0


In [15]:
print(a[::-1])

[0 9 8 7 6 5 4 3 2 1]


In [16]:
print(a[-4:])

[7 8 9 0]


In [17]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
print(n[n>2])

[3 4 5 6 7 8 9]


In [19]:
print(np.sum(n,axis=0))#column wise

[12 15 18]


In [20]:
print(np.sum(n,axis=1))#row wise

[ 6 15 24]


In [21]:
print(np.mean(n,axis=0))

[4. 5. 6.]


In [22]:
print(np.mean(n,axis=1))


[2. 5. 8.]


In [23]:
s = np.array([8,36,2,1,6,74,367])
s

array([  8,  36,   2,   1,   6,  74, 367])

In [24]:
print(np.sort(s))

[  1   2   6   8  36  74 367]


In [25]:
print(np.sort(s)[::-1])#desending order

[367  74  36   8   6   2   1]


In [26]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [31]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [39]:
b = a.reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [40]:
x = b.flatten()
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [44]:
x1 = b.ravel()#uses same ID
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [43]:
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [45]:
x = b.flatten(order="c")
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [46]:
x = b.flatten(order="F")
print(x)

[ 0  4  8  1  5  9  2  6 10  3  7 11]


In [47]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(arr1,arr2)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]


In [48]:
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [49]:
np.hstack((arr1,arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
row = int(input())
col = int(input())
matrix = [[int(input()) for i in range(col)] for j in range(row)] #creating a matrix


In [1]:
import pandas as pd
df = pd.read_csv('DataFrames/weather.csv')
df

day  temprature  windspeed   event
0   1/1/2021        32.0        6.0    Rain
1   1/4/2021         NaN        9.0   Sunny
2   1/5/2021        28.0        NaN    Snow
3   1/6/2021         NaN        7.0     NaN
4   1/7/2021        32.0        NaN    Rain
5   1/8/2021         NaN        NaN   Sunny
6   1/9/2021         NaN        NaN     NaN
7  1/10/2021        34.0        8.0  Cloudy
8  1/11/2021        40.0       12.0   Sunny

In [2]:
df.interpolate()

day  temprature  windspeed   event
0   1/1/2021   32.000000       6.00    Rain
1   1/4/2021   30.000000       9.00   Sunny
2   1/5/2021   28.000000       8.00    Snow
3   1/6/2021   30.000000       7.00     NaN
4   1/7/2021   32.000000       7.25    Rain
5   1/8/2021   32.666667       7.50   Sunny
6   1/9/2021   33.333333       7.75     NaN
7  1/10/2021   34.000000       8.00  Cloudy
8  1/11/2021   40.000000      12.00   Sunny

In [3]:
import sqlite3
conn = sqlite3.connect('ds.sqlite')
cursor = conn.cursor()
print('Opened DB successfully')

Opened DB successfully


In [10]:
cursor.execute('create table student(\
    ID   INT   PRIMARY KEY   NOT NULL,\
    Name   TEXT   NOT NULL);')
cursor.close()

In [12]:
cursor.execute('insert into student values (1, venom)')
cursor.execute('insert into student values (2, carnage)')
cursor.execute('insert into student values (3, Anti-Venom)')

ProgrammingError: Cannot operate on a closed cursor.